### ISSUE TITLE
Is there a way to change perplexity?

### ISSUE THREAD

**Issue by breelege** [YosefLab/VISION#100]
I was going to run my small prelim dataset through vision to try it out (87 single cells) and when I run: 
vis <- analyze(vis) 
I get an error: 
Projecting data into 2 dimensions...
  Running method 1/1: tSNE30 ...
Error in .check_tsne_params(nrow(X), dims = dims, perplexity = perplexity,  : 
  perplexity is too large for the number of samples

Is there any way to change the perplexity or some other way to address the error?

**Comment by mattjones315** [comment]
Hello,

If I remember correctly, you must have at least (3 x perplexity) samples to
run tSNE correctly. So, given you have 87 samples and trying to run tSNE
with perplexity=30 this is why you're seeing this error. We do not have a
way of tuning the perplexity but there are two options you can use to get
around this:

(1) We have a tSNE10 projection method that uses a perplexity of 10
(2) You can add your own projection coordinates if you would like using the
`addProjection` method.

To avoid running tSNE30 on the data, you should specify the projection
methods that you would like to use with the `projection_methods` argument
in the VISION constructor.
For example, we support UMAP which is a standard alternative to tSNE and
should work fine on your data.

Hope this helps, and please let me know if you have any additional
questions!

Best,
Matt

**Comment by breelege** [comment]
Thank you for the advice, this allowed me to run successfully with both tSNE10 and UMAP.
