### ISSUE TITLE
Question regarding signatures and 'COMP' of latent space. 

### ISSUE THREAD

**Issue by Jeongwoola** [YosefLab/VISION#105]
Hi, thanks for the wonderful package/program.

I have two questions regarding VISION. 

1) In the View:  'Latent Space' what does 'COMP' mean? 

2) Can I plot two signature score onto a single graph? For example, the value of X being signature score of 'HALLMARK_GLYCOLYSIS' and Y being the signature score of "HALLMARK_OXIDATIVE_PHOSPHORYLATION" ? Is there such a code, or a way to do it? 

Thank you very much for providing such a fantastic package.

**Comment by mattjones315** [comment]
Hi @Jeongwoola ,

Apologies for the delay in response.

To answer each of these questions -- "COMP" refers to the component of the latent space. For example, if the latent space were PCA, then 'COMP' would refer to the principal components. 

The VISION UI does not support plotting two signatures against one another, but you can extract the signature scores form the `object@sigScores` slot. This is a dataframe that stores all of the signature scores, and you can do many things with these scores.

Please let me know if you have any additional questions.

Best,
Matt
