### ISSUE TITLE
Trouble visualizing signature enrichments. 

### ISSUE THREAD

**Issue by tcswarbear** [YosefLab/VISION#106]
Hello, 

I'm missing the signature tab when I'm trying to view my results after running Vision on an existing Seurat Object.  

sig1 <- read.table("sig1.txt", quote="\"", comment.char="",col.names = "Gene")
sig2 <- read.table("sig2.txt", quote="\"", comment.char="",col.names = "Gene")

sig1 <- createGeneSignature(name = "sig1", sigData = sig1)
sig2 <- createGeneSignature(name = "sig2", sigData = sig2)

MySignatures <- c(sig1,sig2)
vision.obj <- Vision(subset.CD8, signatures = MySignatures, projection_methods = NULL)
vision.obj <- analyze(vision.obj)
viewResults(vision.obj)

![Vision](https://user-images.githubusercontent.com/48106476/150825424-6113d44c-8212-4191-9f61-92c922b0abef.png)

Thank you!
Alex

**Comment by deto** [comment]
It looks like you're creating teh signature objects in an unexpected way - see the example in createGeneSignature docs: https://yoseflab.github.io/VISION/reference/createGeneSignature.html
