### ISSUE TITLE
Installation requires a package that cannot be found...

### ISSUE THREAD

**Issue by SathiyaNManivannan** [YosefLab/VISION#110]
Hello,

I am trying to install VISION on a Ubuntu 18.04.5 LTS system. I using R version 4.1 (from rocker). I am getting the following error.
``
> remotes::install_github("YosefLab/VISION")
Downloading GitHub repo YosefLab/VISION@HEAD

* checking for file ‘/tmp/RtmpEKqRjw/remotes721f29998/YosefLab-VISION-7712042/DESCRIPTION’ ... OK
* preparing ‘VISION’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘VISION/docs’
Removed empty directory ‘VISION/vignettes/web_only’
Omitted ‘LazyData’ from DESCRIPTION
* building ‘VISION_3.0.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘VISION’ ...
** using staged installation
** libs
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG -DROUT -lgopm -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-EhEK7K/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Geary.cpp -o Geary.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG -DROUT -lgopm -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-EhEK7K/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG -DROUT -lgopm -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-EhEK7K/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Utilities.cpp -o Utilities.o
g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-z,relro -o VISION.so Geary.o RcppExports.o Utilities.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-VISION/00new/VISION/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘phanghorn’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
``

The require package phanghorn could not be found anywhere. There is a closely named phangorn package in R. Please help with troubleshooting this error!

Thanks,

Sincerely,

Sathiya

**Comment by mattjones315** [comment]
Hi @SathiyaNManivannan,

It should be good to go now. Let me know if you have any other issues.

Thanks!

-Matt
