### ISSUE TITLE
loe dependency no longer on CRAN?

### ISSUE THREAD

**Issue by bbimber** [YosefLab/VISION#130]
Hello - 

I was trying to install VISION and the loe package, which is a dependency of VISION, is apparently removed from CRAN: https://cran.r-project.org/web/packages/loe/index.html.

Would you consider changing your DESCRIPTION to point to a github repo for loe, such as: https://github.com/cran/loe? Or perhaps there is a more elegant option?

**Comment by deto** [comment]
Looked into this today - turns out, we no longer use the `loe` dependency anyways.  I have removed it and generated a new release.  Let me know if there are any issues.
