### ISSUE TITLE
Errors during package installation

### ISSUE THREAD

**Issue by jasoncrucify** [YosefLab/VISION#131]
Installing package into ‘/shared/home/zzhou2023/R/x86_64-conda-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
ERROR: dependency ‘loe’ is not available for package ‘VISION’
* removing ‘/shared/home/zzhou2023/R/x86_64-conda-linux-gnu-library/4.3/VISION’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp7tmZnV/fileea80479965d8e/VISION_3.0.1.tar.gz’ had non-zero exit status

frequent errors while installation in different platforms i.e. Mac, PC or Linux....

**Comment by deto** [comment]
Looked into this today - turns out, we no longer use the `loe` dependency anyways.  I have removed it and generated a new release.  Let me know if there are any issues.

**Comment by jasoncrucify** [comment]
Thx a lot
So which release I should use then? 2.10 is what is written in GitHub.
Could you provide any code for installation?

Best,

**Comment by deto** [comment]
Where is 2.10 referenced?

On the main README, we recommend using:

```
library(devtools)
install_github("YosefLab/VISION")
```

To install, which should grab the latest commit by default.  Though you could also pass it `tag = "v3.0.2' to fix the version to the latest release (at this time).

**Comment by jasoncrucify** [comment]
Thx a lot

Indeed the it is working and those packages with errors recommended 2.10 in their pages.

It works now

Thanks again
