### ISSUE TITLE
Rtsne.multicore (referenced in the landing page) has recently been deprecated

### ISSUE THREAD

**Issue by allonw** [YosefLab/VISION#36]
Rtsne.multicore is now deprecated by https://github.com/jkrijthe/Rtsne/tree/openmp

See:
https://github.com/RGLab/Rtsne.multicore/commit/7b4f8c6640e9188552e17acc440a6614b19d4189

**Comment by deto** [comment]
Thanks for the heads up - we're actually not using Rtsne.multicore anymore - just haven't updated the README on this yet.  

Unfortunately, the replacement is only a branch in the Rtsne repo - makes it difficult for users to automatically install it!
