### ISSUE TITLE
Documentation on micro-pooling algorithm?

### ISSUE THREAD

**Issue by majorkazer** [YosefLab/VISION#43]
Heyo!

Is there any documentation on how your micro-pooling algorithm works? Is there a way to force it to only pool within specific factor-combinations of meta-data variables?

Thanks!
Sam

**Comment by mattjones315** [comment]
Hey Sam! 

We just made some tweaks to enable users to create their own pools by micro-pooling within certain meta-data variables. While VISION's analysis won't explicitly handle this (as we prefer to only support fully unbiased clustering and it's just easier to give users the freedom to micro-pool for each of their own use cases), we fully understand why people would want to only cluster within certain classes, such as cases and controls. As such, we have exported the applyMicroClustering method which can create pools for you. You can refer to the new vignette in the repository to see what exactly the micro-pooling algorithm does and how it's applied to Vision objects. Hope that helps, and please let me know if you have any other questions! 

Best,
Matt

**Comment by majorkazer** [comment]
Thanks Matt! I will take a look and report any issues!

**Comment by deto** [comment]
Closing.  Now, more detailed documentation on everything is live here:
- https://yoseflab.github.io/VISION/
