### ISSUE TITLE
Mouse gene names in expression matrix or signatures

### ISSUE THREAD

**Issue by toddknutson** [YosefLab/VISION#53]
I tried to use VISION with a gene expression matrix where the `rownames(my_matrix)` are mouse gene name nomenclature (e.g. Ccl5, Gzma, etc.). I supplied a list of custom gene signatures in similar mouse gene name nomenclature (e.g. Ccl5, Gzma, etc.). After running `vis <- Vision(my_matrix, signatures = custom_mouse_sigs_list)` to build my analysis, it appears that my `vis@sigData` slot has been heavily subsetted. This slot only retained some genes from some signatures, and dropped many genes from many signatures. Only uppercase genes were retained in `vis@sigData`.

I think this problem is related to the following line of code that converts the input expression matrix rownames to uppercase on import. 

https://github.com/YosefLab/VISION/blob/5c085cbdb153aa328efd4b203be229150b2ad349/R/methods-Vision.R#L97

Later, when comparing the "now converted to uppercase" matrix rownames against mouse gene names (which are provided as mixed case) in the signatures list, only the uppercase genes are retained. 

https://github.com/YosefLab/VISION/blob/5c085cbdb153aa328efd4b203be229150b2ad349/R/methods-Signature.R#L11

For now, I just converted all my mouse gene signatures lists to uppercase with `topper()` before running Vision. For example:

    custom_mouse_sigs_list_UPPERCASE <- lapply(custom_mouse_sigs_list, function(x) {names(x@sigDict) <- toupper(names(x@sigDict)); return(x)})

    vis <- Vision(my_matrix, signatures = custom_mouse_sigs_list_UPPERCASE)

This seems to have solved the problem.

**Comment by deto** [comment]
Thanks for bringing it to our attention!

Can you tell me more about how you created your signatures?  If they are supplied as a file, the genes should be upper-case'd automatically and if the 'Signature' constructor is used, they should also be upper-case'd.  Though it's always possible there is a bug in one of these paths.  

Alternately, if you built them more manually (e.g., create an empty Signature object and then modify it's sigDict), then I can see how this could result in genes that weren't case-normalized.  I didn't imagine users would do it this way, but easy enough to add in an extra check to support it.

**Comment by toddknutson** [comment]
Sure no problem!

I used the [msigdbr](https://cran.r-project.org/web/packages/msigdbr/vignettes/msigdbr-intro.html) R package. It provides an easy way to get the MSigDB gene sets converted for other species. For example, I used this command to get a data frame with all the gene sets, including a column for the mouse-specific gene names:

```
library(msigdbr)
mm_msigdb <- msigdbr(species = "Mus musculus")
```
This data frame includes a column for `human_gene_symbol` which is uppercase by default, and a `gene_symbol` column that is specific to mouse nomenclature. I used the mouse names because they are more compatible with my mouse gene expression names (i.e. the `rownames(matrix)`). 

I selected two columns from the full `mm_msigdb ` data frame, then I used the `nest` function to collapse all `gene_symbol` values for each geneset.  

```
library(tidyverse)
library(purrr)
mm_msigdb_symbol_list <- mm_msigdb %>%
	dplyr::select(one_of("gs_name", "gene_symbol")) %>%
	nest(one_of("gene_symbol")) 
```

Then I created a little custom function to get the current gene set name and it's associated genes. I created a vector of 1s, where the `names()` are the gene names. Finally, I used your `VISION::createGeneSignature()` function to create the gene signature object.

```
f <- function(i, ont_list) {
	curr_gs_name <- ont_list[i, ]$gs_name[[1]]
	gs <- ont_list[i, ]$data[[1]]  %>% pull(1)
	len <- length(gs)
	# Create vector of 1s
	gs_vect <- rep(1, len)
	# Name the vector with gene names
	names(gs_vect) <- gs
	sig <- VISION::createGeneSignature(name = curr_gs_name, sigData = gs_vect)
	return(sig)
}
```

I used the `purrr::map()` function (or `lapply`) to apply this custom function to each gene set. This results in a list of "Signatures" objects. I then made all the gene names uppercase.
 
```
mm_msigdb_symbol_list_sig <- purrr::map(seq_along(mm_msigdb_symbol_list$gs_name), f, ont_list = mm_msigdb_symbol_list)

class(mm_msigdb_symbol_list_sig[[1]])
# [1] "Signature"
# attr(,"package")
# [1] "VISION"

mm_msigdb_symbol_list_sig_UPPER <- lapply(mm_msigdb_symbol_list_sig, function(x) {names(x@sigDict) <- toupper(names(x@sigDict)); return(x)})
```

Finally, used this list of gene signatures with the `Vision()` function.

```
vis <- Vision(matrix,
              signatures = mm_msigdb_symbol_list_sig_UPPER)

```

Please let me know if you need any other details! Thanks again for Vision -- it's pretty cool!

**Comment by deto** [comment]
Thanks for the details - I didn't know about msigdbR and it seems very useful!

I think I found the issue too - I thought that createGeneSignature was calling a separate function which actually checks the signature entries and upper-cases them, but it looks like it's just creating the Signature object directly - bypassing this step.  An easy fix, though.  Thanks again for taking the time to report the issue.
