### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by deepseq** [YosefLab/VISION#58]
Hi, 

Thank you for the excellent tool. But I met some problems with running it. I followed the Trajectory Model tutorial, but when I ran the command, it dropped the error message below. I cannot understand it. Could you please help with that?

Part of Commands :

vis <- Vision(scaled, signatures = c("sample.gmt"), meta = meta, latentTrajectory = model)
vis <- addProjection(vis, "MDS", model$dimred[,c(1,2)])

options(mc.cores = 24)
vis <- analyze(vis)

The Error is :

Clustering signatures...

fitting ...
  |================================================================| 100%
Evaluating local consistency of signatures within trajectory model...

Error in .local(object, ...) : unused argument (K)

I am not sure what the argument (K) is

Thanks in advance.

**Comment by mattjones315** [comment]
Hello, 

Thank you for using Vision and bringing this to our attention! We tracked this issue down to a small bug in our codebase, which we believe we have now fixed on our master branch. You should be able to proceed by reinstalling Vision from there and restarting the Vision analysis. 

Thank you again, and do let us know if there's anything else we can help with. 

Best,
Matt
