### ISSUE TITLE
broken docs

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/VISION#62]
https://yoseflab.github.io/VISION/articles/Signatures.html

This is broken?

**Comment by mattjones315** [comment]
Looks like this works:
https://yoseflab.github.io/VISION/articles/web_only/Signatures.html

How did you get directed to your link?

-Matt

**Comment by romain-lopez** [comment]
here !
https://yoseflab.github.io/VISION/articles/VISION-vignette.html

**Comment by deto** [comment]
Thanks Romain!  I *think* I just fixed this, but it takes the Github CDN a little bit to update the pages so it's still not showing up.  Will check again in a few hours.

**Comment by deto** [comment]
Fixed by #63
