### ISSUE TITLE
Toy data to accompany the vignette

### ISSUE THREAD

**Issue by sinanassiri** [YosefLab/VISION#70]
Dear Vision team,

First off, thanks for developing this highly needed tool! I can't seem to find the count data from the vignette ("data/expression_counts.txt.gz") anywhere on this repository. Please advise.

Thanks,
Sina

**Comment by mattjones315** [comment]
Hi Sina, 

Apologies here for the late response. I hope you were able to find the data in the meantime, but if not, you can find it in VISION/vignettes/data/ -- here's the link: https://github.com/YosefLab/VISION/tree/master/vignettes/data

Thanks for using VISION! 

-Matt
