### ISSUE TITLE
Problem creating VISION object from a Seurat Object. "Signatures" is an unused argument.

### ISSUE THREAD

**Issue by euclidjd** [YosefLab/VISION#74]
I am following the general VISION pipeline below in R to generate a VISION object, using a Seurat Object as input data:

signatures <- c("data/h.all.v5.2.symbols.gmt")
vision.obj <- Vision(seurat.obj, signatures = signatures)
vision.obj <- analyze(vision.obj)
viewResults(vision.obj)

This was what I used. .gmt file was saved to my R working directory:

immune.signiture <- c("c7.all.v7.0.symbols.gmt")
T537_Acute_Vis <- Vision(T537_Acute, signitures = immune.signiture)

But I always get this error message, telling me that "signatures" isn't an argument when using Vision(). 

> T537_Acute_Vis <- Vision(T537_Acute, signitures = immune.signiture)
Importing counts from obj[["RNA"]]@counts ...
Normalizing to counts per 10,000...
Importing Meta Data from obj@meta.data ...
Importing latent space from Embeddings(obj, "pca") using first 50 components
Error in .local(data, ...) : 
  unused argument (signitures = "c7.all.v7.0.symbols.gmt")

Is there something I'm doing wrong? Any help would be appreciated!

**Comment by deto** [comment]
From your code snippet, it looks like you may have misspelled `signature`.  Can you verify??

**Comment by euclidjd** [comment]
Apologies for the unnecessary post! "Signatures" was indeed misspelled. For some reason, I simply didn't notice. It is working now.

**Comment by deto** [comment]
No problem - good luck with your work!
