### ISSUE TITLE
How to host VISION html on web?

### ISSUE THREAD

**Issue by toddknutson** [YosefLab/VISION#75]
I realize this may not be the correct place to post this question, but could you please suggest any way to host the VISION html page on the web for anyone to access? I'm not looking for any specifics, but are you aware of any hosting companies that make it easy for R sessions to run in the background?

I noticed that you have a "live" example of your tool [http://s133.cs.berkeley.edu:7703](http://s133.cs.berkeley.edu:7703) and I'd like to do something similar for my data.

Sorry for the open ended question! Thanks!

**Comment by mattjones315** [comment]
Hi Todd, 

Thanks for asking this! This is a very common questions I receive from users. We currently host the report on our machines by using this line of code from within an R session:

```r
require(VISION)
# vis is a vision object that has already been analyzed 
viewResults(vis, host='0.0.0.0', port=8224, browser=F)
```

This will host a session at port 8224, so if it were being hosted on our s133 machine, you could access this report via http://s133.cs.berkeley.edu:8224.

I recommend you start this session from within `tmux` or some equivalent, that way it'll run in the background even after you've disconnected your local machine from the server.

Importantly, accessing the report via the weblink will require the same privileges as if you were logging onto the server. In other words, if your server requires you to be connected to a VPN to log on, you'll most likely need to be connected to the VPN to access the web report. 

Hope that helps, and please let me know if you have any other questions! 

-Matt

**Comment by toddknutson** [comment]
Hi Matt,

Great, thanks for your help! I'll give this a try on our University system. 

However, maybe you or someone else might know how to host the Vision object using a cloud platform (e.g. Netlify, GitHub pages, etc.). I'm somewhat familiar with hosting a static site, but not a site that is running R in the background. This might be a question for another place -- but I just wanted to post here as well, in case others are trying to share their Vision results to a wide audience online.  

Thanks again!

**Comment by mattjones315** [comment]
Hi Todd,

No problem! I hope this works on your University system.

I'm not familiar with any way of hosting the Vision report on a cloud
platform, but this would be really cool. If you do find a way of doing
this, it'd be fantastic if you could share that here.

Let me know if the current solution works for you though, and if so I'll
close the issue.

Thanks!
Matt
