### ISSUE TITLE
Using VISION on Windows

### ISSUE THREAD

**Issue by acherman** [YosefLab/VISION#77]
Firstly, thanks for this tool! It's received glowing reviews from the researchers I've helped use it!

I'm passing along an error that occurred when using VISION with Windows 10 Pro and R 3.6.3 from CRAN. I assume this error will happen anywhere that `getOptions("mc.cores", 2L)` returns a value > 1, but it happened to this user when performing DE testing. Specifically, when calling the [`matrix_wilcox_cpp` function](https://github.com/YosefLab/VISION/blob/master/R/Utilities.R#L247) 

The error was: 

`<simpleError in mclapply(seq_len(nrow(data)), function(i) {    uz <- wilcox_subset(as.numeric(data[i, ]), cluster_num, cluster_denom)    return(unlist(uz))}, mc.cores = jobs): 'mc.cores' > 1 is not supported on Windows>`

If others encounter this issue, the simple solution is to set the `MC_CORES` environment variable **_prior_** to loading any libraries, which is done like so:

```
Sys.setenv("MC_CORES" = 1L)

library(VISION)

getOption("mc.cores", 2L)
[1] 1

```

Then everything works as expected!

**Comment by deto** [comment]
Thanks for reporting this issue!

I've made a change that should prevent the error in the future (it'll just fall back to 1 core by default).  Also, I've updated the documentation where it mentions setting the options('mc.cores'=N) option to specify that this should be either omitted or set to 1 on Windows.
