### ISSUE TITLE
Issue during analysis step

### ISSUE THREAD

**Issue by 10xMaria** [YosefLab/VISION#78]
Hi, 

I am trying out Vision for the first time. 
I am using my Seurat object as input, default assay set to "RNA". 

When running vision.obj <- analyze(vision.obj), I get the following error after the "Evaluating signature scores on cells..." process has completed: Error in do.call(rbind, allScoresBatches) : 
  second argument must be a list. 

Any idea on how to fix this? 

Thanks!

**Comment by mattjones315** [comment]
Hello, 

Can you provide more information on all of your input files and a minimal example of the function calls that lead to this error? 

It sounds like signatures may not have been included in your Vision session, but I can't be sure until I see your workflow. 

Thank you! 

-Matt

**Comment by 10xMaria** [comment]
Hi Matt, 

Thanks for getting back to me.
I think you were right, when I obtained the error I used the "all gene sets" download file from MSigDB (msigdb.v7.1.symbols.gmt). I since tried it with the separate data sets (hallmark, BioCarta) and those worked perfectly fine. Glad that it was an easy fix!

Best, 
Maria
