### ISSUE TITLE
No Signatures Present

### ISSUE THREAD

**Issue by pmcerlean-1** [YosefLab/VISION#80]
Dear VISION team,

I've used VISION on a published scRNA-Seq data set (GSE135893) downloaded and imported as a seaurat.obj as outlined in the tutorial. 

I have 3 signatures, 1 custom and 2 from MSigDB.

The analysis seems to run well enough but when I launch the results the 'Signatures' option is missing (attached)? Other functions such as searching for Genes and DE are working. 

There were a few warnings about dropping some of the metadata but don't think that is the issue. 

Could it be these signatures aren't enriched in the data or some other issue? 

FYI I'm running my analysis using RStudio on my institutions HPC. 

Kind regards,

Peter

![Missing Signatures Option](https://user-images.githubusercontent.com/66616814/84014842-dac60d80-a972-11ea-9433-a567842894a3.png)

**Code:**

> sig <- createGeneSignature(name = "IPF Diff Reg Genes", sigData = "/VISION/Diff Exp Meth Genes.gmt")
> 
> sig1 <- createGeneSignature(name = "Hypoxia", sigData = "/VISION/Hypoxia gene set.gmt")
> 
> sig2 <- createGeneSignature(name = "Glycolysis", sigData = "/VISION/Glycolysis gene set.gmt")
> 
> mysignatures <- c(sig, sig1, sig2)
> mysignatures
[[1]]
An object of class "Signature"
Slot "sigDict":
                             <NA> 
"/VISION/Diff Exp Meth Genes.gmt" 

Slot "name":
[1] "IPF Diff Reg Genes"

Slot "source":
[1] "user-defined"

Slot "metaData":
[1] ""

[[2]]
An object of class "Signature"
Slot "sigDict":
                          <NA> 
"/VISION/Hypoxia gene set.gmt" 

Slot "name":
[1] "Hypoxia"

Slot "source":
[1] "user-defined"

Slot "metaData":
[1] ""

[[3]]
An object of class "Signature"
Slot "sigDict":
                             <NA> 
"/VISION/Glycolysis gene set.gmt" 

Slot "name":
[1] "Glycolysis"

Slot "source":
[1] "user-defined"

Slot "metaData":
[1] ""
> seurat.obj <-readRDS(file = "ILD_scRNASeq.rds")
> vision.obj <- Vision(seurat.obj, signatures = mysignatures, projection_methods = NULL)
Importing counts from obj[["RNA"]]@counts ...
Normalizing to counts per 10,000...
Importing Meta Data from obj@meta.data ...
Importing latent space from Embeddings(obj, "pca") using first 50 components

Using 19510/33694 genes detected in 0.10% of cells for signature analysis.
See the `sig_gene_threshold` input to change this behavior.

Dropping 'orig.ident' from meta data as it is of type 'character' and has more than 20 unique values.  If you want to include this meta data variable, convert it to a factor before providing the data frame to Vision
Dropping 'Sample_Name' from meta data as it is of type 'character' and has more than 20 unique values.  If you want to include this meta data variable, convert it to a factor before providing the data frame to Vision
Dropping 'seurat_clusters' from meta data as it is of type 'character' and has more than 20 unique values.  If you want to include this meta data variable, convert it to a factor before providing the data frame to Vision
Dropping 'celltype' from meta data as it is of type 'character' and has more than 20 unique values.  If you want to include this meta data variable, convert it to a factor before providing the data frame to Vision
Over 100000 input cells detected.  Enabling micropooling with max 10 cells per pool.
Adding Visualization: Seurat_pca
Adding Visualization: Seurat_umap
> vision.obj <- analyze(vision.obj)
Beginning Analysis

Performing micro-pooling on 114396 cells with a target pool size of 10
    Using supplied latent space with 50 components
    Performing initial coarse-clustering...
    Further partitioning coarse clusters...
    Micro-pooling completed reducing 114396 cells into 11441 pools
    Aggregating data using assigned pools...completed

Clustering cells...completed

Projecting data into 2 dimensions...

Evaluating signature scores on cells...

Creating 0 background signature groups with the following parameters:
     sigSize sigBalance
  signatures per group: 3000
Computing KNN Cell Graph in the Latent Space...

Evaluating local consistency of signatures in latent space...

  |==================================================================| 100%, Elapsed 01:17:27
  |=====================================================================| 100%, Elapsed 00:01
Clustering signatures...

fitting ...
  |====================================================================================| 100%
Computing differential signature tests...

  |=====================================================================| 100%, Elapsed 00:00
  |=====================================================================| 100%, Elapsed 00:26
Computing correlations between signatures and latent space components...

  |=====================================================================| 100%, Elapsed 00:02
Analysis Complete!

> viewResults(vision.obj)

**Comment by deto** [comment]
My apologies for the delay!

It looks like the error is how you are creating the signatures.  The createGeneSignature function is made for the situation where you have a list of genes in R and want to wrap them into a signature object.

If you already have .gmt files, you can just specify those when creating the Vision object like this:

```
mysignatures <- c(
   "VISION/Diff Exp Meth Genes.gmt", 
   "VISION/Hypoxia gene set.gmt". 
   "VISION/Glycolysis gene set.gmt"
)
vision.obj <- Vision(seurat.obj, signatures = mysignatures, projection_methods = NULL)
```
Should work as long as those paths are relative to the current directory you are running in.  And I'm assuming each .gmt file is the correct format (one row per signature).  You can also just group multiple signatures into the same .gmt file by combining the rows, but it's fine to keep them separate too if you prefer that organization.

**Comment by pmcerlean-1** [comment]
Hi David, 

Thanks for the reply. Seems to have done the trick. 

However I seem to be missing the cell type annotations as was mentioned in the warning:

_Dropping 'celltype' from meta data as it is of type 'character' and has more than 20 unique values. If you want to include this meta data variable, convert it to a factor before providing the data frame to Vision_

Any ideas why its doing this?

Best,

Peter

**Comment by mattjones315** [comment]
Hi Peter, 

Did you try converting this column from 'character' to 'factor' as suggested in the warning? 

-Matt

**Comment by deto** [comment]
Closing stale issue.
