### ISSUE TITLE
addProjection doesn't work properly

### ISSUE THREAD

**Issue by kokitsuyuzaki** [YosefLab/VISION#81]
Thanks for nice tool.

I found that `tSNE30` is performed even if I specified the lower coordinates in advance by `addProjection` function.
For example, I tried to specify my original lower dimensions (`tsne_dim`)
but `tSNE30` was performed.

```r
> vis <- addProjection(vis, "tSNE", tsne_dim)
> vis <- analyze(vis)
Beginning Analysis

Computing a latent space for expression data...

Determining projection genes...
    Applying Threshold filter...removing genes detected in less than 1453 cells
      Genes Retained: 2628
    Applying Fano filter...removing genes with Fano < 2.0 MAD in each of 30 bins
      Genes Retained: 426

Clustering cells...completed

Projecting data into 2 dimensions...
  Running method 1/1: tSNE30 ...
```

**Comment by mattjones315** [comment]
Thanks for using Vision and the positive feedback!

The reason why the analysis pipeline is running tSNE again is that it's one
of the default projections passed to the Vision constructor through the
projection_methods argument. If you don't want to run any projections, you
can construct the object as so:

vis <- Vision(..., projection_methods = c(), ...)

You can also read more about this here
<https://yoseflab.github.io/VISION/reference/VISION-class.html>.

Thanks again, and let me know if this fixes the issue.

-Matt

**Comment by kokitsuyuzaki** [comment]
Thanks for your quick reply.
I could confirm that `tSNE30` was skipped by the empty projection_methods and addProjection.

```r
vis <- Vision(scaled_del, signature=gmtfile, projection_methods=c())
vis <- addProjection(vis, "tSNE", tsne_dim)
vis <- analyze(vis)
Beginning Analysis

Computing a latent space for expression data...

Determining projection genes...

    Applying Threshold filter...removing genes detected in less than 1453 cells
      Genes Retained: 2628
    Applying Fano filter...removing genes with Fano < 2.0 MAD in each of 30 bins
      Genes Retained: 426

Clustering cells...completed

Projecting data into 2 dimensions...

Evaluating signature scores on cells...
```
