### ISSUE TITLE
Feature Request: export figures in different file formats

### ISSUE THREAD

**Issue by acherman** [YosefLab/VISION#85]
I'm curious about the feasibility of adding the option to export plots from the GUI in more than just .png format (e.g. pdf, tiff, etc...)? I poked around for a bit in the source and couldn't quite figure out where the export happens.

**Comment by mattjones315** [comment]
Hello, this export is on the plotly backend and so we didn't have much control over this. Unfortunately the most straightforward workaround right now if you'd like vectorized images is to load the signature scores (or other meta data) into an external session and use a plotting library available there. (FYI - you can access the signature scores from the processed vision object through the `@SigScores` attribute). We'll look into this further and get back to you though, thanks for reaching out with this question! 

-Matt
