### ISSUE TITLE
Get top 10 enriched pathways per seurat assigned cluster

### ISSUE THREAD

**Issue by danmoore1987** [YosefLab/VISION#92]
Hi David,

Great tool! I have a likely stupid question.

How would you go about to get the top 10 significant enriched pathways per designated meta data? I know that "getSignatureAutocorrelation" gets back the top enriched pathways overall, but I want to get the top 10 enriched pathways per seurat assigned cluster.

Thank you!

**Comment by deto** [comment]
Do you want (for example), signatures that have higher scores in cluster X vs the rest?

For that, see the `getSignatureDifferential` function: https://yoseflab.github.io/VISION/reference/getSignatureDifferential.html
